### ISSUE TITLE
Landscape profile integration

### ISSUE THREAD

**Issue by ashelkovnykov** [ashelkovnykov/urbit-chess#10]
Right now, I've setup the frontend challenge/game cards to use an image of a knight piece of the player's color. Perhaps we should add to/replace it with the opponents sigil?

[azimuth.network](https://azimuth.network/erc721/0.svg) has `.svg` images of each sigil available. The default is white-on-black, I'm not sure if they also have black-on-white. If they do, that could be a good replacement:
```
white knight -> black-on-white sigil
black knight -> white-on-black sigil
```
Another issue is that `azimuth.network` only has sigils for galaxies, stars, and planets. So maybe moon/comet users would default to the current knight images?

**Comment by bonbud-macryg** [comment]
Could also add sigils/avatars to the cards in the Friends list.

**Comment by ashelkovnykov** [comment]
Changed issue to "Landscape profile integration". We should be using people's nicknames and profile pictures in addition to the white/black knight, as that's likely how people using `%chess` will be most familiar with each other.
