### ISSUE TITLE
support multiple kelvins

### ISSUE THREAD

**Issue by tomholford** [ashelkovnykov/urbit-chess#107]
Currently the build.sh script assumes a single kelvin version:

```sh
# Build sys.kelvin
echo "[%zuse $KELVIN]" > $DESK_DIR/sys.kelvin
```

Now that an app can declare support for multiple kelvins, this needs to be refactored. Perhaps as part of #106.

**Comment by ashelkovnykov** [comment]
Does it actually? Adding support for a new kelvin means that:
- The UF cut a release candidate with backwards incompatible changes
- We (the community of everyone interested in maintaining `%chess`) took a look at it
- We determined that the changes do not affect `%chess`
- We need to add a PR which includes the new kelvin version and bumps the minor version

Is this really that different from decrementing the single supported kelvin and bumping the minor version? People downstream won't have their `%chess` break - they just won't be able to get the latest version until they update Arvo.

I guess it could be useful in the sense that people on older kelvin versions can receive the latest updates without needing to upgrade to the latest version of Arvo, but then the question is "why don't they want to upgrade to the latest Arvo?" This is also an unsafe development practice, as now contributors/maintainers would always have to keep the following question in mind when reviewing code: "Do these changes introduce code not available in older kelvin versions?"

The goal of `%chess` is to be a protocol (in a sense): regardless of specific versions of `%chess` or Arvo, any players on the same major version should always be able to play against each other. An additional failsafe is that if two players cannot play against each other, the failure should happen during challenge/game setup, not during/after moves have been made.
