### ISSUE TITLE
Docker upgrade on MacOS breaks the build.sh

### ISSUE THREAD

**Issue by brbenji** [ashelkovnykov/urbit-chess#149]
### Error 1
After the Docker app upgrade, running `bin/build.sh -s zod` would produce the output below and not build anything.
``` shell
❯ bin/build.sh -s zod
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            BuildKit is currently disabled; enable it by removing the DOCKER_BUILDKIT=0
            environment-variable.

2023/09/07 08:10:29 must use ASL logging (which requires CGO) if running as root
```
### Solution 1
In the `bin/build.sh` file comment out the line with `DOCKER_BUILDKIT=0` and uncomment out the line without `DOCKER_BUILDKIT=0` in it.
``` shell
# sudo docker build --tag ${DOCKER_IMAGE}:${VERSION_FULL} .
sudo DOCKER_BUILDKIT=0 docker build --tag ${DOCKER_IMAGE}:${VERSION_FULL} .
```
like this.
```shell
sudo docker build --tag ${DOCKER_IMAGE}:${VERSION_FULL} .
# sudo DOCKER_BUILDKIT=0 docker build --tag ${DOCKER_IMAGE}:${VERSION_FULL} .
```

### Error 2
``` shell
❯ sudo bin/build.sh -s zod
[+] Building 0.2s (2/3)                                            docker:desktop-linux
[+] Building 0.3s (3/3) FINISHED                                   docker:desktop-linux
 => [internal] load build definition from Dockerfile                               0.0s
 => => transferring dockerfile: 807B                                               0.0s
 => [internal] load .dockerignore                                                  0.0s
 => => transferring context: 2B                                                    0.0s
 => ERROR resolve image config for docker.io/docker/dockerfile:1                   0.2s
------
 > resolve image config for docker.io/docker/dockerfile:1:
------
Dockerfile:1
--------------------
   1 | >>> # syntax=docker/dockerfile:1
   2 |
   3 |     FROM node:slim
--------------------
ERROR: failed to solve: error getting credentials - err: exit status 1, out: ``
```
_Note: I had to start running `sudo` for potentially unrelated reasons._

### Solution 2
Open `~/.docker/config.json` and change the `"credsStore":` line from `"credsStore": "desktop",` to `"credsStore": "osxkeychain",`.

My config.json file looks like this.
``` json
{
	"auths": {},
	"credsStore": "osxkeychain",
	"currentContext": "desktop-linux"
}
```
### Error 3
mkdir operation not permitted. This one could be my fault for messing with folder ownership.
``` shell
docker: Error response from daemon: error while creating mount source path '/host_mnt/Users/nordus/dev/urbit/chess-tree/browse-completed-games/build/frontend': mkdir /host_mnt/Users/nordus/dev/urbit/chess-tree/browse-completed-games/build/frontend: operation not permitted.
```
No solution just yet. All the other solutions above might be a mistake.

**Comment by ashelkovnykov** [comment]
@bonbud-macryg Do you still need `DOCKER_BUILDKIT=0` for you MacOS version?

**Comment by bonbud-macryg** [comment]
Upgraded to `Docker Desktop 4.22.1 (118664)`. When I delete everything and try Solution 1:

```
§ chess  ./bin/build.sh -s dev && rm -rf ../gals/dev/chess/* && ./bin/install.sh -p ../gals -s dev
[+] Building 0.3s (2/3)                                        docker:desktop-linux
[+] Building 0.5s (3/3) FINISHED                               docker:desktop-linux
 => [internal] load build definition from Dockerfile                           0.0s
 => => transferring dockerfile: 807B                                           0.0s
 => [internal] load .dockerignore                                              0.0s
 => => transferring context: 2B                                                0.0s
 => ERROR resolve image config for docker.io/docker/dockerfile:1               0.4s
------
 > resolve image config for docker.io/docker/dockerfile:1:
------
Dockerfile:1
--------------------
   1 | >>> # syntax=docker/dockerfile:1
   2 |     
   3 |     FROM node:slim
--------------------
ERROR: failed to solve: error getting credentials - err: exit status 1, out: ``
```

**Comment by ashelkovnykov** [comment]
@bonbud-macryg That's the same error as @brbenji got afterwards (Error 2). What if you apply the same solution that he did?

**Comment by ashelkovnykov** [comment]
@bonbud-macryg Ping on the above question

**Comment by bonbud-macryg** [comment]
### Standard

First build of chess `0.9.5` with the newest Docker version `4.24.0 (122432)`. No issues. Build command is just `./bin/build.sh -s bud`.

### Removing `DOCKER_BUILDKIT=0`

Fails to build with this error:
```
[+] Building 0.3s (2/3)                                        docker:desktop-linux
[+] Building 0.4s (3/3) FINISHED                               docker:desktop-linux
 => [internal] load .dockerignore                                              0.0s
 => => transferring context: 2B                                                0.0s
 => [internal] load build definition from Dockerfile                           0.0s
 => => transferring dockerfile: 807B                                           0.0s
 => ERROR resolve image config for docker.io/docker/dockerfile:1               0.4s
------
 > resolve image config for docker.io/docker/dockerfile:1:
------
Dockerfile:1
--------------------
   1 | >>> # syntax=docker/dockerfile:1
   2 |     
   3 |     FROM node:slim
--------------------
ERROR: failed to solve: error getting credentials - err: exit status 1, out: ``
```

It says `docker:desktop-linux` but this is the macOS ARM version. I get this same error whether I'm building for the first or second time having deleted everything from Docker.

@brbenji Do you want to update your local `urbit-chess` repo, update to the newest Docker version, and try building as above?

**Comment by bonbud-macryg** [comment]
I've just built successfully with Solution 1 + 2, building chess `0.9.5` using the newest Docker version `4.24.0 (122432)`. Solution 1 alone caused the same error above. @brbenji Want to upgrade everything and try again?

**Comment by brbenji** [comment]
I'll give it a shot in half an hour.

**Comment by brbenji** [comment]
After two long upgrades into docker `v4.24.0` the `bin/build -s zod` worked fine. I did have to increase the amount of disk space for docker to use, but that shouldn't be related to this.

I tested all the combination. I did it in a strange order but here is what I got. 

- ### Solution 2 only. BUILT
  _received the same deprecation error, but it worked fine anyway._
- ### Solution 2 + Solution 1. BUILT
  _no errors._
- ### Solution 1 only. FAILED
  _received a credentials error_
- ### Neither Solution. BUILT
  _oddly this one worked, it gave the same deprecation error._

**Comment by bonbud-macryg** [comment]
I can build as well with Solution 2 only; no `DOCKER_BUILDKIT=0` required. I don't get a warning about deprecation.

With the eslint integration in #152 I'd say there's no reason for people to use Docker who don't *really* want to use Docker. If @ashelkovnykov can't add some kind of configuration to make Docker use `osxkeychain` for credentials on macOS, maybe we just document that you'll have to make this change to your `docker.config.json` file if you want to use Docker on macOS.
