### ISSUE TITLE
Colour issues with new board visuals

### ISSUE THREAD

**Issue by bonbud-macryg** [ashelkovnykov/urbit-chess#150]
The new board visuals introduce some issues where the colour of the squares interferes with the chessground UI. Including:
* Some black pieces are barely legible against the black squares.
* The dots that highlight possible moves are barely visible against black squares.
* The red glow around a king in check is invisible against the red squares.

These are game-breaking issues. My preferred solution has two parts:
* Overwrite/amend some of chessground's UI behaviour (e.g. the colour of piece destinations should contrast with whatever is below them)
* Amend the chess piece assets so that they don't conflict with board colours.

Amending the pieces should be easy as they're .svg files, which makes them easy to pull into something like Affinity Designer and change the colours. While I'm editing to fix the issues, I can also amend the pieces to look more consistent with the Chess 1.0 UI.

**Comment by ashelkovnykov** [comment]
We might want to include custom square CSS settings for each of our boards, as in [chessground.brown.css](https://github.com/lichess-org/chessground/blob/master/assets/chessground.brown.css). Editing the SVGs for the pieces to have outlines sounds like the best approach for improving the pieces.

**Comment by bonbud-macryg** [comment]
Outlines were another approach I considered; I think it's one of those things were we won't know if it looks good or not until we try it.

**Comment by ashelkovnykov** [comment]
Resolved by #167
