### ISSUE TITLE
Booted to practice menu after game conclusion

### ISSUE THREAD

**Issue by ashelkovnykov** [ashelkovnykov/urbit-chess#2]
Since there is currently no way to view completed games, completing a game (through draw or mate) boots both players back to their respective practice boards.

**Comment by ashelkovnykov** [comment]
Blocked by #6

**Comment by bonbud-macryg** [comment]
If we implement a Lichess-style panel as suggested in the description of #37, then one UI change that occurs upon the game's completion is that panel changing from an "active game" state to an "archive game" state. So maybe this isn't necessarily _blocked_ by #37, but it would be sensible to address that first.

**Comment by ashelkovnykov** [comment]
@bonbud-macryg Agreed - would be easier to get #37 resolved first, then copy the JS for the active game panel and simplify it to render completed games.

**Comment by ashelkovnykov** [comment]
Resolved by #109
