### ISSUE TITLE
`%docs` documentation

### ISSUE THREAD

**Issue by ashelkovnykov** [ashelkovnykov/urbit-chess#21]
Add documentation files to integrate `%chess` documentation with the [`%docs` app](https://github.com/tinnus-napbus/docs-app) (like `man` for Urbit).

**Comment by bonbud-macryg** [comment]
Blocked by #28, #29, #30.

**Comment by ashelkovnykov** [comment]
Issue unblocked

**Comment by bonbud-macryg** [comment]
@ashelkovnykov I could make a start on this soon, though it should probably be the last Milestone 1 issue that gets checked off. What should it cover, and who's the intended reader?

**Comment by ashelkovnykov** [comment]
Removed from Chess Bounty milestones; no point documenting the API until it stops changing massively (case in point, #144)
