### ISSUE TITLE
Remove abandoned matches from log

### ISSUE THREAD

**Issue by ashelkovnykov** [ashelkovnykov/urbit-chess#27]
If a peer breaches, uninstalls `%chess`, or otherwise abandons a game, it would be nice to be able to remove it from the web interface. This only has significance for untimed matches, as timed matches will eventually receive a "timeout" notification. Whether the match is ranked or unranked, a player should be able to abandon it at any time:
- unranked matches: just delete game from state
- ranked matches: show warning that player may lose rating as a result

This also has significance for cases where a breach or error occurs on the timing/ELO server(s). Ideally, `%chess` could dump games on a breach notification from a ship acting as timekeeper or rating monitor. Alternatively, the player could manually abandon timed games at any time with a warning: that he may appear to lose to the opponent/server and may lose rating as a result.

This task will involve minor frontend work ("abandon game" button and warning pop-ups), but mostly backend work.

**Comment by bonbud-macryg** [comment]
This should come after #25 which implements ranked/unranked game logic. #25 being dependent on #6 and #2.

**Comment by ashelkovnykov** [comment]
@bonbud-macryg Yeah, probably easier to push this to after the ELO server code is written

**Comment by bonbud-macryg** [comment]
@ashelkovnykov Is this issue ready to move forward now that we've got the test suite for the Elo server? We now know pretty much exactly what it's going to do and how it's going to do it.

**Comment by ashelkovnykov** [comment]
I'm going to remove this from Milestone 1, since it's blocked on `%telos` integration. This issue is also very low in importance: given that by the end of the bounty, users will be able to resign, will be able to mark matches as unrated and unrecorded, and will be able to play timed matches instead of correspondence, it's almost never going to be needed (I predict).
