### ISSUE TITLE
Clean up comments

### ISSUE THREAD

**Issue by bonbud-macryg** [ashelkovnykov/urbit-chess#32]
Clean up comments across the /sur, /app, /lib/chess.hoon files following the Chess Style Guide, which will come out of the ~2022.9 Chess Improvements Bounty. Not under the remit of the bounty work.

**Comment by ashelkovnykov** [comment]
I'm going to close this just because it's not an actionable issue. Deciding when code is well-documented enough is too vague; if there's particular sections of code that should be documented, that's actionable.
