### ISSUE TITLE
Add panel to see previous moves, view previous board states

### ISSUE THREAD

**Issue by ashelkovnykov** [ashelkovnykov/urbit-chess#37]
Add a panel (I'm thinking to the left-hand side of the screen) which contains the list of moves made in the game so far. The user can click on an old move to see the board state as it was at that time. I'm referring to something like this:

![example](https://user-images.githubusercontent.com/4383244/189220228-94cd49fc-2076-4cd1-856e-b4031516ee2b.png)

The panel on the right-hand side of this screenshot from lichess (obviously, the timer & ELO rating needn't be present [yet]; however, moving the "offer draw" and "resign" buttons to this panel would be a good idea).

A lot of synergy between this feature request and the #20 feature request. Mostly frontend work, some very small backend work possible.

**Comment by ashelkovnykov** [comment]
Issue submitted on behalf of `~soldel-ridlun`

**Comment by rovmug-ticfyn** [comment]
Is the idea with this feature that a player could request to undo back to any particular board state? I've thought about #20 as merely undoing one move at a time. Would this be a bulk undo, or just a way to browse previous states?

**Comment by ashelkovnykov** [comment]
@rovmug-ticfyn Your interpretation is correct: #20 is about sending requests to the opponent to undo one move at a time. This issue is about being able to see the move history for both players while playing, and to be able to view the state of the board after that move (just to view it; if a player is viewing a past board state, there should be no way to interact with it).

**Comment by bonbud-macryg** [comment]
In the frontend sketch, this left-hand "Game Panel" actually does allow undoing an arbitrary no. of moves. When the player is viewing a previous state, an "Undo" button appears below the panel. If clicked, it sends a request to the opponent to undo to that move.

Implementing this right away (so, no stopgap solution where we decouple this from #20) would require amending #20 to undo *to a specific move*, maybe expressed as a `@ud` of the move number (e.g. 20) which we could use to replace the `list` of `chess-move`s in `chess-game` with its first 20 items.

(cc: @rovmug-ticfyn)

**Comment by bonbud-macryg** [comment]
We'll have to be mindful of frontend-backend syncing in this issue.

This panel could update with every new move from our opponent, but what if we make a move and it errors out on our ship? Ideally our move is only added to the panel/chessboard after it's been successfully computed on the backend, but how long does that take? It would cause a UX issue; anything that has to happen *fast* should happen on the frontend.

Perhaps a move should be added to the frontend board and panel instantly, but the relevant error branches in `/app/chess.hoon` should tell the frontend to undo that move if they fire.

**Comment by ashelkovnykov** [comment]
@bonbud-macryg 
I prefer the design decision to only undo one move at a time. I understand that in a few specific cases it would be inconvenient to have to go through an "undo handshake" multiple times to go back multiple moves, but the vast majority of undo requests are to undo a single move. It would also remove processing power from the person approving an undo request: he would always know that such a request is to go back to the opponent's ply on the previous move.

Regarding undoing moves that failed to fire, React should take care of this natively, as a failed move will cause a state update, which will in turn cause the board to be re-rendered.

**Comment by ashelkovnykov** [comment]
Reopening - the issue is not resolved until the panel actually shows past moves and we can click on them to view past board states
