### ISSUE TITLE
Allow users to browse completed games

### ISSUE THREAD

**Issue by ashelkovnykov** [ashelkovnykov/urbit-chess#6]
`%chess` stores completed games, but only exposes them through `peek`s. I'm not actually sure if the Urbit http-api allows `peek`s, or what the secure way to implement this feature is (since you don't want foreign ships being able to read your past games at will). Definitely requires frontend work, may require backend work. Will also fix issue #2 in the process.

**Comment by brbenji** [comment]
@ashelkovnykov For this issue. Do we want players to be able to simply have a list of archived games to see the metadata for? Or do we want to allow players to pull up archived games and then step through every move of that game on the practice board?

**Comment by bonbud-macryg** [comment]
It should be trivial to scroll/"step" through every move of a game once we implement #37, which does the same for the game you're currently playing.

**Comment by ashelkovnykov** [comment]
@brbenji The latter - as @bonbud-macryg pointed out in the comments for #2, there's no hard dependency between #6 & #2 and #37, but it would be easier to complete them after #37 is merged.

**Comment by ashelkovnykov** [comment]
Thought occurred to me: we're probably going to want to handle this with scries and not subscriptions. As the number of games a user has played increases, fetching literally all of them on startup up, including every move and FEN position, will be untenable.

**Comment by bonbud-macryg** [comment]
Yeah, I mentioned this issue in the "#37, \#2, and \#6 Plan" post in Design Notes but didn't suggest any particular solution. We might want to do a little of both.

Maybe the frontend subscribes to a wire that'll inform it of new games added to `completed-games`; when it first subscribes, `on-watch` just returns the result of scrying the most recent (let's say) 25 items in `completed-games`. When the player scrolls to the bottom of that list, it scries the next 25.

Question there is how best to tell the backend which range of games we want. The only thing that occurs to me right now is an arm which takes a range (or a starting index: how many completed games are currently loaded on the frontend) and scries that range in `completed-games`.

[A section of App School II](https://developers.urbit.org/guides/core/app-school-full-stack/7-app-logic#getting-entries) covers a similar problem in some detail, on loading a certain number of journal entries at one time. Linked page is the actual code but some of the thinking behind it might be in earlier pages.
