### ISSUE TITLE
Search games archive

### ISSUE THREAD

**Issue by ashelkovnykov** [ashelkovnykov/urbit-chess#65]
Search set of games in archive to find specific a game. Search criteria ideas:
- opponent
- side
- date
- result

Blocked by #6

**Comment by brbenji** [comment]
We could add 
- event

This would allow people to do a simple kind of tagging.

To be exhaustive of what’s available in a `chess-game`:
- site
_I can see this being used to name whatever frontend version of %chess is used. Or probably more useful would be if chess tournaments could change this. Ex: `site='Battle Chess 2023!`_ 
- round
_This one is a stretch, but perhaps it’s useful to view all the games you lost or won within 20 moves._

**Comment by brbenji** [comment]
@ashelkovnykov I have an efficiency question.

Since the structure of the chess archive is `archive=(map @dau chess-game)` and `chess-game` contains all the relevant search info, will it be inefficient for a search to unpack every single `chess-game` in the `archive` map, gather up what matches the search, and then send the result?

I wouldn’t have thought about it except that there’s a cheat for date data, because we can just search the `@dau` directly in the `archive`, and send the matching `chess-game`s. 

**to start**
For the sake of just getting started, I’ll assume that %chess will send the whole `archive` to the frontend on a `peek` and that’s where we’ll handle searching through it.

**Comment by ashelkovnykov** [comment]
@brbenji

I originally titled this issue "Search games archive", but I think that this may be a misnomer, depending on how we want to approach the heart of the request.

What do we actually want to do? We have archived games in `%chess` and we want to be able to browse them from the frontend. We'd also like to be able to filter the full list of games by one or more criteria, to make finding the one which interests use easier. Depending on how many games we have played and how many filters are applied, there may be too many to display at one time, so we want to browse them a few at a time.

The criteria which we would like to use for filtering (at least to begin with) are:
- Date
- Opponent
- Side played
- Result

"Site", "event", and "round" are not long for this world and should be ignored (this type of metadata is better handled outside of the app, unless tournaments have built-in support). Your tagging idea is a good idea, but shouldn't be included in the first draft. "Event" is already being used as a description, and we'll probably want to keep that (though rename it). One possibility is to use the description as a makeshift tag (i.e. filter by name) before a generic tagging system is implemented.

It's important to note that the starting date & time of the game is a natural ordering, and that we would never want to re-order the data: just filter it.

There are two ways we could accomplish this:
1. "Filter" approach
    1. Send all archived game metadata (but not moves/FENs) to frontend on initial subscribe
    2. Frontend can filter/page data however it wants
    3. When user selects an archived game, frontend sends scry to `%chess` for the moves/FENs of just that one archived game
        - It's possible to cache this data in the session or local storage, so we only have to do one scry per game
2. "Search" approach
    1. Search queries are setup on the frontend, through combinations of filters and display limits
    2. User hits "search" button, and the query is sent to `%chess`
    3. `%chess` sends all data found for the query in the archive to the frontend
    4. Frontend visualizes the results however it wants
    5. Moves & FENs for returned games already available
        - Possible to cache this data too, as described for `1.3`

Approach one seems like the far superior approach to me. Not because [it's faster on the frontend](https://github.com/thecommons-urbit/chess/pull/109#discussion_r1097998520) (it's not, or at least it eventually won't be), but because:
1. It's a cleaner separation of the duties of the frontend and backend. For example, pagination should be a purely frontend concern (don't need to worry on the backend about "get all games that match these filters, but not the first 8 because I already saw those").
    1. The backend:
        1. has game state for live games and archived games
        2. can export both kinds of state
        3. can update the state of live games
    2. The frontend:
        1. visualizes backend states
        2. nicely formats pokes/scries to the backend through a GUI
2. It's much more simple to implement
    1. Very simple to do a single pass over the full list of archived games and drop games that don't meet the filter requirements.
    2. While not the most efficient solution, unless the games archive is truly massive, it is not so inefficient as to matter.

With that in mind, let's re-evaluate what our needs are from the games archive:
- We want to be able to fetch metadata for each game, ordered by decreasing date
- We want to be able to fetch the moves/FEN positions for any random game

Given that we want both ordered insertion/traversal and random lookup, I think your idea to convert the archive to `ordered-map` aka `mop` is correct.

**Comment by bonbud-macryg** [comment]
Agreed that approach one is better, it keeps the backend simple.
