### ISSUE TITLE
Sort active games

### ISSUE THREAD

**Issue by ashelkovnykov** [ashelkovnykov/urbit-chess#75]
Sort by:
- date
- ship (alphabetical)
- ship (Azimuth point number)

**Comment by bonbud-macryg** [comment]
I *have* found myself wishing that the active games would sort themselves by the last update, so if my opponent ~sampel-palnet moves then my game with him moves to the top of the list. Old, untimed correspondence games the opponent might have forgotten about would gradually slide down to the bottom of the list.

**Comment by ashelkovnykov** [comment]
@bonbud-macryg That's the best sorting mechanism, and I didn't even think of it: "date of last move".

Another good one could be "time remaining", once hooked up to the timing server.
