### ISSUE TITLE
Challenge with random sides shows white knight to opponent (as if challenger requesting to play as black)

### ISSUE THREAD

**Issue by ashelkovnykov** [ashelkovnykov/urbit-chess#85]
When receiving a challenge, the information about which side you would play as is displayed as an image of a white knight (if you would play white) or a black knight (if you would play black). If the challenger selected random sides, the challenge card still displays a white knight. This is confusing and incorrect. Instead, for a random match, there should be some other image (e.g. a dice face).

**Comment by bonbud-macryg** [comment]
Other obvious ideas for this image might be a question mark or a knight with one half white and the other black, to match the knight images displayed elsewhere.
